- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Update APT cache
  apt: 
    update_cache: yes
    #force_apt_get: true

  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Install python-pip.
  package:
   name: "{{ item.1 }}"   
   state: latest
  with_indexed_items: "{{ python_pip_packages }}"  
  when: (not skip_docker_py) or (ansible_os_family == 'Debian'
    and ansible_python_version is version_compare('2.6.0', '>=')
    and ansible_python_version is version_compare('2.7.9', '<'))

- name: Install the Python SNI support packages.
  package:
   name: "{{ item }}"
   state: present
  with_items: "{{ python_sni_support_packages }}"
  when: ansible_os_family == 'Debian'
    and ansible_python_version is version_compare('2.6.0', '>=')
    and ansible_python_version is version_compare('2.7.9', '<')

- name: Install the Python SNI python-pip dependencies.
  pip:
   name: '{{ python_sni_pip_dependencies }}'
   state: present
  with_items: "{{ python_sni_pip_dependencies }}"
  when: ansible_os_family == 'Debian'
    and ansible_python_version is version_compare('2.6.0', '>=')
    and ansible_python_version is version_compare('2.7.9', '<')

# Install the Docker Engine
- include: docker_engine.yml
  when: not skip_engine

# Install docker-py
- include: docker_py.yml
  when: not skip_docker_py

# Adds the Docker admin users to the Docker group
- include: docker_group.yml
  when: not skip_group

# Setup the Docker Swarm Cluster
- include: swarm_cluster.yml
  when: not skip_swarm

# Add docker swarm workers
- include: docker_swarm_worker.yml

# Add prometheus service
- include: docker_swarm_services.yml